# Generated by Django 5.0.4 on 2024-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
